name: ci-golang-workflow
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  check-application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.15,1.14]
    steps:
    # uses são actions que serão executadas
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
        # versão do go
          go-version: ${{matrix.go-version}}
          # comando que será executado
      - run: go test
      - run: go run math.go

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: walbersonmv/goapp:latest
        