name: ci-golang-workflow
on: [push]
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
    # uses são actions que serão executadas
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
        # versão do go
          go-version: 1.23
          # comando que será executado
      - run: go test
      - run: go run math.go
        